/// Fractional index utility — mirrors server/app/utils/fractional_index.py.
///
/// Alphabet: '0'–'9' then 'a'–'z' (base-36, lowercase).
/// Starting position: 'n' (index 23).
///
/// All functions produce non-empty strings and maintain strict lexicographic
/// ordering for the same inputs as the Python implementation.
class FractionalIndex {
  FractionalIndex._();

  static const String _chars = '0123456789abcdefghijklmnopqrstuvwxyz';
  static const int _base = 36;

  // Pre-compute char → index map.
  static final Map<String, int> _charIndex = {
    for (int i = 0; i < _chars.length; i++) _chars[i]: i,
  };

  // Mid-point character: index 18 = 'i'.
  static final String _midChar = _chars[_base ~/ 2]; // 'i'

  // Starting position returned by [first].
  static const String _firstPos = 'n';

  // ---------------------------------------------------------------------------
  // Public API
  // ---------------------------------------------------------------------------

  /// Return a position string for the first (and only) item in an empty list.
  static String first() => _firstPos;

  /// Return a position string that sorts strictly after [a].
  ///
  /// Appending the mid character always produces a string lexicographically
  /// greater than [a] (the appended character extends beyond the end of [a]).
  static String after(String a) {
    if (a.isEmpty) throw ArgumentError('position string must not be empty');
    return a + _midChar;
  }

  /// Return a position string that sorts strictly before [a].
  ///
  /// Walks from the rightmost character looking for one that can be
  /// decremented.  If found, decrements it and truncates.
  static String before(String a) {
    if (a.isEmpty) throw ArgumentError('position string must not be empty');

    final chars = a.split('');
    for (int i = chars.length - 1; i >= 0; i--) {
      final idx = _charIndex[chars[i]]!;
      if (idx > 0) {
        chars[i] = _chars[idx - 1];
        return chars.sublist(0, i + 1).join();
      }
    }

    // All characters are '0' — should not occur in normal usage.
    throw ArgumentError(
      "Cannot compute before('$a'): all characters are at minimum '0'. "
      'This position was not generated by this module.',
    );
  }

  /// Return a position string that sorts strictly between [a] and [b].
  ///
  /// Requires [a] < [b] lexicographically.
  static String between(String a, String b) {
    if (a.isEmpty || b.isEmpty) {
      throw ArgumentError('position strings must not be empty');
    }
    if (a.compareTo(b) >= 0) {
      throw ArgumentError("between() requires a < b, got '$a' >= '$b'");
    }

    final maxLen = a.length > b.length ? a.length : b.length;
    final aPadded = a.padRight(maxLen, '0');
    final bPadded = b.padRight(maxLen, '0');

    final result = <String>[];

    for (int i = 0; i < maxLen; i++) {
      final ca = aPadded[i];
      final cb = bPadded[i];
      final ia = _charIndex[ca]!;
      final ib = _charIndex[cb]!;

      if (ia == ib) {
        result.add(ca);
        continue;
      }

      // Characters differ at position i.
      final mid = (ia + ib) ~/ 2;
      if (mid > ia) {
        result.add(_chars[mid]);
        return result.join();
      }

      // Adjacent characters (ia + 1 == ib) — extend beyond a's position.
      // aPadded[i:] + midChar is always:
      //   > a: appending chars beyond a's end makes it lexicographically greater
      //   < b: result starts with ca which is < cb = bPadded[i]
      result.addAll(aPadded.substring(i).split(''));
      result.add(_midChar);
      return result.join();
    }

    // [a] padded equals [b] padded, meaning [b] is longer — append mid char.
    return a + _midChar;
  }
}
